language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:codegear/release
  - sudo apt-get update -qq
  - sudo apt-get install -qq premake4

before_script:
  - pushd build && premake4 gmake && popd

script:
  - pushd build/gmake && make -f test.make config=release64 && popd
  - pushd bin && ./unittest_release_x64_gmake && popd

notifications:
  recipients:
    - marcus@doo.net
  email:
    on_success: change
